services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-http-server
    ports:
      - "8000:8000"

  swagger-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-swagger
    ports:
      - "8100:8100"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
<<<<<<< HEAD:docker-compose.yml



# docker rm mysql-container
# docker-compose up -d
# docker-compose down
# docker-compose up
# docker-compose up --build
# docker-compose restart
=======
  pgadmin_data:
>>>>>>> BA-01-fixed/docker-url:.docker/docker-compose.yml
